// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by VSIX Synchronizer
// </auto-generated>
// ------------------------------------------------------------------------------
namespace ClassBuilder
{
	using System;

	/// <summary>
	/// Helper class that exposes all GUIDs used across VS Package.
	/// </summary>
	internal sealed partial class PackageGuids
	{
		public const string guidClassBuilderPackageString = "94017910-9c76-41e4-954c-ef075c1f85fc";
		public static Guid guidClassBuilderPackage = new Guid(guidClassBuilderPackageString);

		public const string guidClassBuilderPackageCmdSetString = "73fb9981-cf4f-47e9-aca5-ace34a62e685";
		public static Guid guidClassBuilderPackageCmdSet = new Guid(guidClassBuilderPackageCmdSetString);

		public const string guidClassBuilderPackageCmdSet1String = "de465d9f-a8b1-43f1-931d-61ee59bbffaf";
		public static Guid guidClassBuilderPackageCmdSet1 = new Guid(guidClassBuilderPackageCmdSet1String);
	}
	/// <summary>
	/// Helper class that encapsulates all CommandIDs uses across VS Package.
	/// </summary>
	internal sealed partial class PackageIds
	{
		public const int MyMenuGroup = 0x1020;
		public const int BuilderCommandId = 0x0100;
	}
}